// Tests for code that isnt published to npm
const unpublishedTests = [
  //
  "packages/avatar/test/avatar-lit.test.js",
  "packages/custom-field/test/custom-field-lit.test.js",
  "packages/custom-field/test/keyboard-lit.test.js",
  "packages/custom-field/test/slot-wrapper-lit.test.js",
  "packages/email-field/test/validation-lit.test.js",
  "packages/details/test/details-lit.test.js",
  "packages/icon/test/icon.test.js",
  "packages/login/test/login-form-lit.test.js",
  "packages/login/test/login-overlay-lit.test.js",
  "packages/login/test/login-submit-lit.test.js",
  "packages/number-field/test/number-field-lit.test.js",
  "packages/number-field/test/validation-lit.test.js",
  "packages/number-field/test/value-commit-lit.test.js",
  "packages/number-field/test/value-control-buttons-lit.test.js",
  "packages/polymer-legacy-adapter/test/grid-editor.test.js",
  "packages/progress-bar/test/progress-bar-lit.test.js",
  "packages/radio-group/test/radio-button-lit.test.js",
  "packages/radio-group/test/radio-group-keyboard-navigation-lit.test.js",
  "packages/radio-group/test/radio-group-lit.test.js",
  "packages/radio-group/test/validation-lit.test.js",
  "packages/split-layout/test/split-layout-lit.test.js",
  "packages/text-area/test/text-area-lit.test.js",
  "packages/text-area/test/validation-lit.test.js",
  "packages/upload/test/a11y-lit.test.js",
  "packages/upload/test/adding-files-lit.test.js",
  "packages/upload/test/file-list-lit.test.js",
  "packages/upload/test/file-lit.test.js",
  "packages/upload/test/keyboard-navigation-lit.test.js",
  "packages/upload/test/slots-lit.test.js",
  "packages/upload/test/upload-lit.test.js",
  "packages/virtual-list/test/lit-lit.test.js",
  "packages/virtual-list/test/lit-renderer-directives-lit.test.js",
  "packages/virtual-list/test/virtual-list-lit.test.js",
];

export default unpublishedTests;
